<a href="https://colab.research.google.com/github/sungkabkim/python_programming/blob/main/Numpy_11%EC%A3%BC%EC%B0%A8_%EA%B9%80%EC%84%B1%EA%B0%9124%EB%B0%95%EC%82%AC_2024285934.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 숙제하기 : Numpy 다음 사이트의 코드를 따라서 코딩

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
!pip3 install numpy

In [ ]:
import numpy as np
a = np.arange(6)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a2 = a[np.newaxis, :]

In [ ]:
a2.shape

(1, 6)

In [ ]:
a.shape

(6,)

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
np.empty(2)

array([1.43522288e-311, 0.00000000e+000])

In [ ]:
np.arange(2,8,2) #start부터 stop "직전"까지 step 간격으로 배열 생성

array([2, 4, 6])

In [ ]:
np.linspace(0, 10, num=5) #start부터 stop까지의 구간을 N개의 동일한 간격으로 나누어 배열을 생성

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
a = 1.

In [ ]:
a

1.0

In [ ]:
type(a)

float

In [ ]:
np.ones(2, dtype=np.int64) #지정한 shape 크기의 배열을 만들고 모든 원소를 1.0으로 채웁니다.

array([1, 1])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0]

array([1, 2, 3, 4])

In [ ]:
a[2]

array([ 9, 10, 11, 12])

In [ ]:
a[1, 3]

np.int64(8)

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
# (depth, rows, columns) 형태

In [ ]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
array_example.ndim # To find the number of dimensions of the array

3

In [ ]:
array_example.size # To find the total number of elements in the array

24

In [ ]:
array_example.shape # To find the shape of your array

(3, 2, 4)

In [ ]:
a = np.arange(6)

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
np.reshape(a, newshape=(1, 6), order='C')

C:\Users\sizip\AppData\Local\Temp\ipykernel_780\1026200341.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a, newshape=(1, 6), order='C')


array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]

In [ ]:
a2.shape

(1, 6)

In [ ]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
row_vector = a[np.newaxis, :]

In [ ]:
row_vector.shape

(1, 6)

In [ ]:
# indexing and slicing

In [ ]:
import numpy as np

In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data

array([1, 2, 3])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:] # 끝에서 두 번째부터 끝까지

array([2, 3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[a < 5] #true인것만 가져오면 됨

array([1, 2, 3, 4])

In [ ]:
print(a < 5)

[[ True  True  True  True]
 [False False False False]
 [False False False False]]


In [ ]:
b = 2

In [ ]:
if b > 5 :
    print("에구 너무 큰데요")
else:
    print("좋아요")

좋아요


In [ ]:
b > 5

False

In [ ]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.nonzero(a < 5)

In [ ]:
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [ ]:
print(list(zip(b[0], b[1])))

[(np.int64(0), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(3))]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
arr1 = a[3:8]

In [ ]:
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

In [ ]:
a1

array([[1, 1],
       [2, 2]])

In [ ]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a2 = np.array([[3, 4],
               [4, 4]])

In [ ]:
a2

array([[3, 4],
       [4, 4]])

In [ ]:
np.concatenate((a1, a2), axis=0)

array([[1, 1],
       [2, 2],
       [3, 4],
       [4, 4]])

In [ ]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 4],
       [2, 2, 4, 4]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
a = np.arange(1, 15)

In [ ]:
a.reshape(2, 7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
x= np.arange(1, 25).reshape(2, 12)

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3)[0] # stack them horizontally with

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [ ]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
# slicing, 매우매우 중요함

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(a[2, 3])

12


In [ ]:
(a[2, 3])

np.int64(12)

In [ ]:
b1 = a[0,:]

In [ ]:
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99

In [ ]:
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2 = a[0,:].copy()

In [ ]:
b2

array([99,  2,  3,  4])

In [ ]:
print(b2)

[99  2  3  4]


In [ ]:
# basic operations

In [ ]:
data = np.array([1, 2])

In [ ]:
ones = np.ones(2, dtype=int)

In [ ]:
data

array([1, 2])

In [ ]:
data + ones

array([2, 3])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
import numpy as np

In [ ]:
data = np.array([1, 2])

In [ ]:
ones = np.ones(2, dtype=int)

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b = np.array(([1, 1], [2, 2]))

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b

array([[1, 1],
       [2, 2]])

In [ ]:
b.sum(axis=1)

array([2, 4])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(data.max())

6


In [ ]:
print(data.min())

1


In [ ]:
print(a)

[1 2 3 4]


In [ ]:
b = np.array(([1, 4], [2, 7], [3, 8]))

In [ ]:
b

array([[1, 4],
       [2, 7],
       [3, 8]])

In [ ]:
b.min(axis=0)

array([1, 4])

In [ ]:
b.max(axis=0)

array([3, 8])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0, 1]

np.int64(2)

In [ ]:
print(data[0,1])

2


In [ ]:
print(data[1:3])

[[3 4]
 [5 6]]


In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
unique_values = np.unique(a) #to print the unique values in your array

In [ ]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values = np.unique(a)

In [ ]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True)

In [ ]:
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [ ]:
unique_values, occurrence_count = np.unique(a, return_counts=True)

In [ ]:
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [ ]:
print(a_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [ ]:
unique_values = np.unique(a_2d)

In [ ]:
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
unique_rows = np.unique(a_2d, axis=0)

In [ ]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

In [ ]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(indices)

[0 1 2]


In [ ]:
print(occurrence_count)

[2 1 1]


In [ ]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr = np.arange(6).reshape((2, 3))

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
reversed_arr = np.flip(arr)

In [ ]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
reversed_arr = np.flip(arr_2d)

In [ ]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [ ]:
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [ ]:
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [ ]:
arr_2d[1] = np.flip(arr_2d[1])

In [ ]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [ ]:
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1 = x.flatten()

In [ ]:
a1[0] = 99

In [ ]:
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a2 = x.ravel()

In [ ]:
a2[0] = 98

In [ ]:
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
